name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
        working-directory: ./job-board-ui

      - run: npm run build
        working-directory: ./job-board-ui

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: mvn clean install -DskipTests
        working-directory: ./job-board-backend
